syntax = 'proto3';

import 'auth/authorization.proto';
import 'auth/session.proto';
import 'auth/token.proto';
import 'auth/user.proto';
import 'shared/shared.proto';

package auth;

service AuthService {
    rpc Register (authorization.RegisterInput) returns (authorization.AuthOutput);
    rpc Login (authorization.LoginInput) returns (authorization.AuthOutput);
    rpc Refresh (authorization.RefreshInput) returns (authorization.AuthOutput);
    rpc Logout (authorization.RefreshInput) returns (shared.Empty);
    rpc Validate (authorization.ValidateInput) returns (authorization.UserPayload);
    rpc ForgotPassword (authorization.ForgotPasswordInput) returns (shared.Empty);
    rpc ResetPassword (authorization.ResetPasswordInput) returns (shared.Empty);
    rpc GetMe (authorization.ValidateInput) returns (authorization.UserEntity);
}

service SessionService {
    rpc GetSessionsByUser (session.AllSessionsByUserInput) returns (session.AllSessionsOutput);
    rpc GetMySessions (session.AllMySessionsInput) returns (session.AllSessionsOutput);
    rpc ChangeSessionLocalName (session.SessionLocalNameInput) returns (session.SessionOutput);
    rpc DeleteSessionById (session.DeleteSessionByIdInput) returns (session.SessionOutput);
    rpc DeleteAllSessions (session.DeleteAllSessionsInput) returns (shared.Empty);
}

service TokenService {
    rpc GetTokensWithPagination (token.GetTokensInput) returns (token.AllTokensOutput);
    rpc GetTokenById (token.TokenByIdInput) returns (token.TokenOutput);
    rpc SetTokenRevoked (token.RevokeTokenInput) returns (token.TokenOutput);
    rpc DeleteTokenById (token.DeleteTokenInput) returns (token.TokenOutput);
    rpc DeleteAllNotActiveTokens (token.DeleteAllNotActiveTokensInput) returns (shared.Empty);
}

service UserService {
    rpc GetAllUsers (user.GetAllUsersInput) returns (user.PaginatedUsersOutput);
    rpc GetUserById (user.GetUserByIdInput) returns (user.UserOutput);
    rpc BlockUser (user.BlockUserInput) returns (user.UserOutput);
    rpc UnblockUser (user.UnblockUserInput) returns (user.UserOutput);
    rpc PromoteToModerator (user.PromoteToModeratorInput) returns (user.UserOutput);
    rpc DemoteFromModerator (user.DemoteFromModeratorInput) returns (user.UserOutput);
    rpc ChangeEmail (user.ChangeEmailInput) returns (user.UserOutput);
    rpc ChangePassword (user.ChangePasswordInput) returns (user.UserOutput);
    rpc SetUserInactive (user.SetUserInactiveInput) returns (shared.Empty);
    rpc ChangeUserToActive (user.ChangeUserToActiveInput) returns (user.UserOutput);
}
