syntax = "proto3";

package tasks;

message Empty {}

message TaskSchema {
  int32 id = 1;
  string name = 2;
  string description = 3;
}

message AllTasks {
  repeated TaskSchema items = 1;
}

message TaskInput {
  string name = 1;
  string description = 2;
}

message TaskById {
  int32 id = 1;
}

message UpdateTaskRequest {
  int32 id = 1;
  string name = 2;
  string description = 3;
}

message ChangeNameRequest {
  int32 id = 1;
  string name = 2;
}

message ChangeDescriptionRequest {
  int32 id = 1;
  string description = 2;
}

service TaskService {
  rpc FindAll (Empty) returns (AllTasks);
  rpc FindById (TaskById) returns (TaskSchema);
  rpc CreateTask (TaskInput) returns (TaskSchema);
  rpc UpdateTask (UpdateTaskRequest) returns (TaskSchema);
  rpc ChangeName (ChangeNameRequest) returns (TaskSchema);
  rpc ChangeDescription (ChangeDescriptionRequest) returns (TaskSchema);
  rpc DeleteTask (TaskById) returns (TaskSchema);
}